### ISSUE TITLE
`mput` add a `--recursive` option?

### ISSUE THREAD

**Issue by shofetim** [TritonDataCenter/node-manta#287]
It would be nice to be able to recursively upload a directory, and all it's contents, to a Manta path. Right now I think the simplest work around is to do something like:

```fish
for i in (find .); mput -p -f $i ~~/public/subpath/subpath/$i; end
```
( That's [fish shell](https://fishshell.com/) syntax)

**Comment by jperkin** [comment]
You might want to check out https://github.com/bahamas10/node-manta-sync

**Comment by bahamat** [comment]
As of v 5.4.0 (#396), the command `msync` is included which will recursively PUT/GET directories.
